export const designers = [
  {
    id: '1',
    name: '김수빈',
    engName: 'soobin Kim',
    email: 'wns@naver.com',
    insta: 'sadasd',
    website: 'sadasd',
    image_1: '../images/하이.png',
    image_2: '../images/하이.png',
  },
  {
    id: '2',
    name: '김수빈',
    engName: 'soobin Kim',
    email: 'wns@naver.com',
    insta: 'sadasd',
    website: 'sadasd',
    image_1: '../images/하이.png',
    image_2: '../images/하이.png',
  },
  {
    id: '3',
    name: '김수빈',
    engName: 'soobin Kim',
    email: 'wns@naver.com',
    insta: 'sadasd',
    website: 'sadasd',
    image_1: '../images/하이.png',
    image_2: '../images/하이.png',
  },
  {
    id: '4',
    name: '김수빈',
    engName: 'soobin Kim',
    email: 'wns@naver.com',
    insta: 'sadasd',
    website: 'sadasd',
    image_1: '../images/하이.png',
    image_2: '../images/하이.png',
  },
  {
    id: '5',
    name: '김수빈',
    engName: 'soobin Kim',
    email: 'wns@naver.com',
    insta: 'sadasd',
    website: 'sadasd',
    image_1: '../images/하이.png',
    image_2: '../images/하이.png',
  },
  {
    id: '6',
    name: '김수빈',
    engName: 'soobin Kim',
    email: 'wns@naver.com',
    insta: 'sadasd',
    website: 'sadasd',
    image_1: '../images/하이.png',
    image_2: '../images/하이.png',
  },
  {
    id: '7',
    name: '김수빈',
    engName: 'soobin Kim',
    email: 'wns@naver.com',
    insta: 'sadasd',
    website: 'sadasd',
    image_1: '../images/하이.png',
    image_2: '../images/하이.png',
  },
  {
    id: '8',
    name: '김수빈',
    engName: 'soobin Kim',
    email: 'wns@naver.com',
    insta: 'sadasd',
    website: 'sadasd',
    image_1: '../images/하이.png',
    image_2: '../images/하이.png',
  },
  {
    id: '9',
    name: '김수빈',
    engName: 'soobin Kim',
    email: 'wns@naver.com',
    insta: 'sadasd',
    website: 'sadasd',
    image_1: '../images/하이.png',
    image_2: '../images/하이.png',
  },
  {
    id: '10',
    name: '김수빈',
    engName: 'soobin Kim',
    email: 'wns@naver.com',
    insta: 'sadasd',
    website: 'sadasd',
    image_1: '../images/하이.png',
    image_2: '../images/하이.png',
  },
  {
    id: '11',
    name: '김수빈',
    engName: 'soobin Kim',
    email: 'wns@naver.com',
    insta: 'sadasd',
    website: 'sadasd',
    image_1: '../images/하이.png',
    image_2: '../images/하이.png',
  },
  {
    id: '12',
    name: '김수빈',
    engName: 'soobin Kim',
    email: 'wns@naver.com',
    insta: 'sadasd',
    website: 'sadasd',
    image_1: '../images/하이.png',
    image_2: '../images/하이.png',
  },
];

export const getDesigner = designerId => {
  return designers.find(({ id }) => id === designerId);
};
