export const designers = [
  {
    id: '1',
    name: '강례모',
    engName: 'Ryemo Kang',
    email: 'fpah0526@naver.com',
    insta: '',
    website: '',
    image_1: '../images/1_thumbnail.png',
    project_1: 1,
    image_2: '../images/2_thumbnail.png',
    project_2: 2,
  },
  {
    id: '2',
    name: '기유림',
    engName: 'Yoolim Ki',
    email: 'yourangi9@naver.com',
    insta: '',
    website: '',
    image_1: '../images/3_thumbnail.png',
    project_1: 3,
    image_2: '../images/4_thumbnail.png',
    project_2: 4,
  },
  {
    id: '3',
    name: '김서진',
    engName: 'Seojin Kim',
    email: 'odrey999@naver.com',
    insta: '4.s2ojin_k1m',
    website: '',
    image_1: '../images/5_thumbnail.png',
    project_1: 5,
    image_2: '../images/6_thumbnail.png',
    project_2: 6,
  },
  {
    id: '4',
    name: '김수민',
    engName: 'Sumin Kim',
    email: 'min61a6@naver.com',
    insta: '',
    website: '',
    image_1: '../images/7_thumbnail.png',
    project_1: 7,
    image_2: '../images/8_thumbnail.png',
    project_2: 8,
  },
  {
    id: '5',
    name: '김수빈',
    engName: 'Soobin Kim',
    email: 'soobnies@gmail.com',
    insta: '',
    website: '',
    image_1: '../images/9_thumbnail.png',
    project_1: 9,
    image_2: '../images/10_thumbnail.png',
    project_2: 10,
  },
  {
    id: '6',
    name: '김수빈',
    engName: 'Subin Kim',
    email: 'tnmaju16@gmail.com',
    insta: '',
    website: '',
    image_1: '../images/8_thumbnail.png',
    project_1: 8,
    image_2: '../images/11_thumbnail.png',
    project_2: 11,
  },
  {
    id: '7',
    name: '김수현',
    engName: 'Suhyeon Kim',
    email: 'kimsuhyeon72@naver.com',
    insta: 'mic_ell7',
    website: '',
    image_1: '../images/12_thumbnail.png',
    project_1: 12,
    image_2: '../images/13_thumbnail.png',
    project_2: 13,
  },
  {
    id: '8',
    name: '김제균',
    engName: 'Jegyun Kim',
    email: 'wprbs1629@naver.com',
    insta: 'zeze_624',
    website: 'https://notefolio.net/zeze624',
    image_1: '../images/14_thumbnail.png',
    project_1: 14,
    image_2: '../images/15_thumbnail.png',
    project_2: 15,
  },
  {
    id: '9',
    name: '김주연',
    engName: 'Jooyeon Kim',
    email: 'tina1705@naver.com',
    insta: '',
    website: '',
    image_1: '../images/2_thumbnail.png',
    project_1: 2,
    image_2: '../images/16_thumbnail.png',
    project_2: 16,
  },
  {
    id: '10',
    name: '김찬미',
    engName: 'Chanmi Kim',
    email: 'chanmiuni@gmail.com',
    insta: '_chanmikim_',
    website: 'https://chansdesign.myportfolio.com/',
    image_1: '../images/17_thumbnail.png',
    project_1: 17,
    image_2: '../images/18_thumbnail.png',
    project_2: 18,
  },
  {
    id: '11',
    name: '김희진',
    engName: 'Heejin Kim',
    email: 'gmlwls731@gmail.com',
    insta: 'white_jin_',
    website: '',
    image_1: '../images/19_thumbnail.png',
    project_1: 19,
    image_2: '../images/20_thumbnail.png',
    project_2: 20,
  },
  {
    id: '12',
    name: '노은채',
    engName: 'Eunchae Noh',
    email: 'nohkate1@gmail.com',
    insta: '',
    website: '',
    image_1: '../images/21_thumbnail.png',
    project_1: 21,
    image_2: '../images/22_thumbnail.png',
    project_2: 22,
  },
  {
    id: '13',
    name: '박온유',
    engName: 'On Yu Park',
    email: 'parkonyu927@gamil.com',
    insta: '',
    website: '',
    image_1: '../images/13_thumbnail.png',
    project_1: 13,
    image_2: '../images/23_thumbnail.png',
    project_2: 23,
  },
  {
    id: '14',
    name: '박채린',
    engName: 'Chaerin Park',
    email: '8_00__@naver.com',
    insta: '',
    website: '',
    image_1: '../images/24_thumbnail.png',
    project_1: 24,
    image_2: '../images/25_thumbnail.png',
    project_2: 25,
  },
  {
    id: '15',
    name: '백송현',
    engName: 'Songhyeon Beck',
    email: 'songgus147@naver.com',
    insta: '_pickax',
    website: '',
    image_1: '../images/20_thumbnail.png',
    project_1: 20,
    image_2: '../images/26_thumbnail.png',
    project_2: 26,
  },
  {
    id: '16',
    name: '변아현',
    engName: 'Ahyeon Byeon',
    email: 'bah8282@naver.com',
    insta: '',
    website: '',
    image_1: '../images/27_thumbnail.png',
    project_1: 27,
    image_2: '../images/28_thumbnail.png',
    project_2: 28,
  },
  {
    id: '17',
    name: '신재은',
    engName: 'Jaeeun Shin',
    email: 'jjaeun.ss@gmail.com',
    insta: 'jaeeun.ss',
    website: '',
    image_1: '../images/29_thumbnail.png',
    project_1: 29,
    image_2: '../images/30_thumbnail.png',
    project_2: 30,
  },
  {
    id: '18',
    name: '안예린',
    engName: 'Yeryn Ahn',
    email: 'yerynahn@naver.com',
    insta: '',
    website: '',
    image_1: '../images/18_thumbnail.png',
    project_1: 18,
    image_2: '../images/31_thumbnail.png',
    project_2: 31,
  },
  {
    id: '19',
    name: '안채희',
    engName: 'Chaehee Ahn',
    email: 'rvhee@naver.com',
    insta: '',
    website: '',
    image_1: '../images/32_thumbnail.png',
    project_1: 32,
    image_2: '../images/33_thumbnail.png',
    project_2: 33,
  },
  {
    id: '20',
    name: '양현지',
    engName: 'Hyeonji Yang',
    email: 'yhyji@naver.com',
    insta: '',
    website: '',
    image_1: '../images/34_thumbnail.png',
    project_1: 34,
    image_2: '../images/35_thumbnail.png',
    project_2: 35,
  },
  {
    id: '21',
    name: '윤선희',
    engName: 'Sunhee Yoon',
    email: 'sunsun411@naver.com',
    insta: '',
    website: '',
    image_1: '../images/30_thumbnail.png',
    project_1: 30,
    image_2: '../images/36_thumbnail.png',
    project_2: 36,
  },
  {
    id: '22',
    name: '이사라',
    engName: 'Sara Lee',
    email: 'sara24ra@naver.com',
    insta: 'leesaraart',
    website: '',
    image_1: '../images/37_thumbnail.png',
    project_1: 37,
    image_2: '../images/38_thumbnail.png',
    project_2: 38,
  },
  {
    id: '23',
    name: '이성현',
    engName: 'Seonghyeon Lee',
    email: 'yonggi.project@gmail.com',
    insta: 'wolfhoo',
    website: 'https://www.behance.net/a01090155871a9, https://notefolio.net/leesh_',
    image_1: '../images/39_thumbnail.png',
    project_1: 39,
    image_2: '../images/40_thumbnail.png',
    project_2: 40,
  },
  {
    id: '24',
    name: '이승미',
    engName: 'Seung mi Lee',
    email: 'tmdal1302@gmail.com',
    insta: '',
    website: '',
    image_1: '../images/9_thumbnail.png',
    project_1: 9,
    image_2: '../images/10_thumbnail.png',
    project_2: 10,
  },
  {
    id: '25',
    name: '이유빈',
    engName: 'Youbin Lee',
    email: 'ubinnys@gmail.com',
    insta: '',
    website: '',
    image_1: '../images/41_thumbnail.png',
    project_1: 41,
    image_2: '../images/42_thumbnail.png',
    project_2: 42,
  },
  {
    id: '26',
    name: '이윤주',
    engName: 'Yoonjoo Lee',
    email: 'yoonlee.eu@gmail.com',
    insta: 'yoon.ee.cone',
    website: 'https://notefolio.net/yoonz, https://www.behance.net/yoonjoo_',
    image_1: '../images/43_thumbnail.png',
    project_1: 43,
    image_2: '../images/44_thumbnail.png',
    project_2: 44,
  },
  {
    id: '27',
    name: '이재연',
    engName: 'Jaeyoun Lee',
    email: '2_jyn@naver.com',
    insta: '',
    website: '',
    image_1: '../images/35_thumbnail.png',
    project_1: 35,
    image_2: '../images/45_thumbnail.png',
    project_2: 45,
  },
  {
    id: '28',
    name: '이정진',
    engName: 'Jungjin Lee',
    email: 'ljj6825@naver.com',
    insta: '',
    website: '',
    image_1: '../images/46_thumbnail.png',
    project_1: 46,
    image_2: '../images/47_thumbnail.png',
    project_2: 47,
  },
  {
    id: '29',
    name: '이지나',
    engName: 'Gina Lee',
    email: 'ginafairy@naver.com',
    insta: '',
    website: '',
    image_1: '../images/47_thumbnail.png',
    project_1: 47,
    image_2: '../images/48_thumbnail.png',
    project_2: 48,
  },
  {
    id: '30',
    name: '이지민',
    engName: 'Jimin Lee',
    email: 'mandu2973@gmail.com',
    insta: '',
    website: '',
    image_1: '../images/49_thumbnail.png',
    project_1: 49,
    image_2: '../images/50_thumbnail.png',
    project_2: 50,
  },
  {
    id: '31',
    name: '이청아',
    engName: 'Chungah Lee',
    email: 'chunga0621@gmail.com',
    insta: '',
    website: '',
    image_1: '../images/9_thumbnail.png',
    project_1: 9,
    image_2: '../images/10_thumbnail.png',
    project_2: 10,
  },
  {
    id: '32',
    name: '이혜나',
    engName: 'Hyena Lee',
    email: 'gpsksla23@naver.com',
    insta: '',
    website: '',
    image_1: '../images/51_thumbnail.png',
    project_1: 51,
    image_2: '../images/52_thumbnail.png',
    project_2: 52,
  },
  {
    id: '33',
    name: '이혜지',
    engName: 'Hyeji Lee',
    email: 'xhxhfh89@naver.com',
    insta: '',
    website: '',
    image_1: '../images/47_thumbnail.png',
    project_1: 47,
    image_2: '../images/53_thumbnail.png',
    project_2: 53,
  },
  {
    id: '34',
    name: '전혜정',
    engName: 'Hye Jeong Jeon',
    email: 'mooon.j03@gmail.com',
    insta: 'full_moo0n_p',
    website: 'https://fullmoo0n.myportfolio.com',
    image_1: '../images/6_thumbnail.png',
    project_1: 6,
    image_2: '../images/54_thumbnail.png',
    project_2: 54,
  },
  {
    id: '35',
    name: '정민혜',
    engName: 'Minhye Jeong',
    email: 'abcd0297@gmail.com',
    insta: '',
    website: '',
    image_1: '',
    image_2: '',
  },
  {
    id: '36',
    name: '정연수',
    engName: 'Yeonsoo Jeong',
    email: 'ssyu212ss@gmail.com',
    insta: '',
    website: '',
    image_1: '../images/55_thumbnail.png',
    project_1: 55,
    image_2: '../images/56_thumbnail.png',
    project_2: 56,
  },
  {
    id: '37',
    name: '정희수',
    engName: 'Heesu Jeong',
    email: '0lmang@naver.com',
    insta: '',
    website: '',
    image_1: '../images/57_thumbnail.png',
    project_1: 57,
    image_2: '../images/58_thumbnail.png',
    project_2: 58,
  },
  {
    id: '38',
    name: '조유은',
    engName: 'Yueun Cho',
    email: 'dbdmstkfkd13@naver.com',
    insta: 'uissilveritme',
    website: '',
    image_1: '../images/59_thumbnail.png',
    project_1: 59,
    image_2: '../images/60_thumbnail.png',
    project_2: 60,
  },
  {
    id: '39',
    name: '진영지',
    engName: 'Youngji Jin',
    email: 'cocomushs2@swu.ac.kr',
    insta: '',
    website: '',
    image_1: '../images/52_thumbnail.png',
    project_1: 52,
    image_2: '../images/61_thumbnail.png',
    project_2: 61,
  },
  {
    id: '40',
    name: '최유리',
    engName: 'Yuri Choi',
    email: 'koreancheeseburger@gmail.com',
    insta: 'yuuu_uuuls',
    website: '',
    image_1: '../images/62_thumbnail.png',
    project_1: 62,
    image_2: '../images/63_thumbnail.png',
    project_2: 63,
  },
  {
    id: '41',
    name: '최혜수',
    engName: 'Haesoo Choi',
    email: 'ilike3333@naver.com',
    insta: 'hsoooh.ae',
    website: '',
    image_1: '../images/64_thumbnail.png',
    project_1: 64,
    image_2: '../images/65_thumbnail.png',
    project_2: 65,
  },
];

export const getDesigner = designerId => {
  return designers.find(({ id }) => id === designerId);
};

export const getDesignerByName = designerName =>
  designers.find(({ name }) => name === designerName);
